[build]
  publish = "."

# Redirect old URLs (we removed gallery/admin)
[[redirects]]
  from = "/gallery"
  to = "/"
  status = 301

[[redirects]]
  from = "/gallery.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 301
