[build]
  command = "npm run build:gallery"
  publish = "."

# ---- Admin SPA (no loops) ----
# Serve the CMS for /admin and anything under /admin/*
[[redirects]]
  from = "/admin"
  to   = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200

# ---- Gallery JSON should never be cached ----
[[headers]]
  for = "/static/gallery.json"
  [headers.values]
  cache-control = "no-store"
