[build]
  publish = "."

# Redirect old URLs so no one hits a 404
[[redirects]]
  from = "/gallery"
  to = "/"
  status = 301

[[redirects]]
  from = "/gallery.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 301
