[build]
  command = "npm run build:gallery"
  publish = "."

# Serve the CMS SPA correctly under /admin
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Gallery JSON should never be cached so uploads show up immediately
[[headers]]
  for = "/static/gallery.json"
  [headers.values]
  cache-control = "no-store"
